### ISSUE TITLE
Subida de imágenes desde registro

### ISSUE THREAD

**Issue by Jendoliver** [Jendoliver/proyecto_dam#12]
Es preciso permitir a los usuarios subir una foto de perfil desde la página de registro, así como anotar en la base de datos la ruta donde se guarda para poder acceder a ella más adelante.

![image](https://cloud.githubusercontent.com/assets/23485344/24117407/6a5007fc-0daa-11e7-95c8-ababc56c15f7.png)

**Comment by XSmoothiexXX** [comment]
El código que está escrito en el cloud9 en el insertor.php es el más optimo para subida de imágenes, ya que le cambia el nombre original al archivo por una id única, pero sigue sin subirse la imagen, sospecho que es por el lugar donde tengo encajado el código, solo faltaria arreglar este error y ya deberia funcionar, en el header de perfiles he arreglado el src de la imagen para que coja la ruta entera y no solo el nombre de la imagen.

   ```
           $tempFile = $_FILES['pic']['tmp_name'];    
		$destDir  = '/front_end/img/users/';
		$destName = uniqid() . '_' . $_FILES['pic']['name'];
		$destFile = $destDir . $destName;

		// El archivo está ahora en la destinacion con un nombre unico 
		move_uploaded_file($tempFile, $destFile);
```
