### ISSUE TITLE
Registro de bandas y locales no funciona

### ISSUE THREAD

**Issue by Jendoliver** [Jendoliver/proyecto_dam#36]
Error en insertBanda/insertMusico (tiene pinta de la primera) y insertGarito. Al haber quitado errorConsulta devuelve 1 y el programa sigue adelante. Debugar consultas

**Comment by Jendoliver** [comment]
TODO: Remove UNIQUE constraint from host

**Comment by Jendoliver** [comment]
@XSmoothiexXX ^^^^

**Comment by XSmoothiexXX** [comment]
Removed UNIQUE constraint from host
